# Generated by Django 4.2.23 on 2026-02-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('MID', 'Mid-term'), ('END', 'End-semester'), ('TEST', 'Test')], max_length=10)),
                ('year', models.PositiveSmallIntegerField(help_text='Year of study (1-4)')),
                ('semester', models.PositiveSmallIntegerField()),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.department')),
            ],
        ),
        migrations.CreateModel(
            name='ExamHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSessionHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_invigilators', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_halls', to='exams.exam')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='exams.examhall')),
            ],
        ),
        migrations.CreateModel(
            name='InvigilationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('REASSIGNED', 'Reassigned')], default='PENDING_CONFIRMATION', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_deadline', models.DateTimeField(blank=True, null=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('exam_session_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.examsessionhall')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_assignments', to='accounts.faculty')),
            ],
        ),
    ]
