# Generated by Django 4.2.23 on 2026-03-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_faculty_must_change_password_loginotp'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, help_text='Faculty teaching this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_exams', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='invigilationassignment',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invigilationassignment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invigilationassignment',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('REASSIGNED', 'Reassigned'), ('EXPIRED', 'Expired')], default='PENDING_CONFIRMATION', max_length=30),
        ),
    ]
