# Generated by Django 4.2.23 on 2026-03-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_faculty_must_change_password_loginotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_exam_subject_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clash_type', models.CharField(max_length=50)),
                ('clash_details', models.TextField()),
                ('suggestion_type', models.CharField(max_length=50)),
                ('suggestion_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('IMPLEMENTED', 'Implemented'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_suggestions', to='exams.exam')),
                ('exam_session_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='exams.examsessionhall')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_suggestions', to='accounts.faculty')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
