# Generated by Django 4.2.23 on 2026-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_allocationsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Year of study (1-4)'),
        ),
        migrations.AlterField(
            model_name='invigilationassignment',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invigilationassignment',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('REASSIGNED', 'Reassigned'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_CONFIRMATION', max_length=30),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_date', 'start_time'], name='exams_exam_exam_da_925b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['department', 'year', 'semester'], name='exams_exam_departm_68d7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='invigilationassignment',
            index=models.Index(fields=['faculty', 'status'], name='exams_invig_faculty_689793_idx'),
        ),
        migrations.AddIndex(
            model_name='invigilationassignment',
            index=models.Index(fields=['status', 'confirmation_deadline'], name='exams_invig_status_0c622d_idx'),
        ),
    ]
