# Generated by Django 4.2.23 on 2026-02-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytimeslot',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of study (1-4)', null=True),
        ),
    ]
