# Generated by Django 4.2.23 on 2026-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year', 'semester', 'code']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'year', 'semester')},
        ),
    ]
