# Generated by Django 4.2.23 on 2026-02-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('timetable', '0004_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'year', 'semester', 'code']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='exams.department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code', 'year', 'semester')},
        ),
    ]
