# Generated by Django 4.2.23 on 2026-03-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_course_code_alter_exam_exam_date_and_more'),
        ('timetable', '0005_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytimeslot',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_slots', to='exams.department'),
        ),
        migrations.AddField(
            model_name='facultytimeslot',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2')], help_text='Semester (1-2)', null=True),
        ),
        migrations.AlterField(
            model_name='facultytimeslot',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], help_text='Year of study (1-4)', null=True),
        ),
    ]
