# Generated by Django 4.2.23 on 2026-03-09 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='facultyactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='facultyactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyactionlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='facultyactionlog',
            index=models.Index(fields=['faculty', '-created_at'], name='logs_facult_faculty_fb15c2_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyactionlog',
            index=models.Index(fields=['action_type'], name='logs_facult_action__13dd76_idx'),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['user', '-created_at'], name='logs_admina_user_id_f6f652_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type'], name='logs_admina_action__18ecf1_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='logs_admina_related_ae017a_idx'),
        ),
    ]
