# Generated by Django 4.2.23 on 2026-03-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_assignment', models.BooleanField(default=True)),
                ('email_assignment_reminder', models.BooleanField(default=True)),
                ('email_leave_status', models.BooleanField(default=True)),
                ('email_system_announcements', models.BooleanField(default=True)),
                ('inapp_new_assignment', models.BooleanField(default=True)),
                ('inapp_assignment_reminder', models.BooleanField(default=True)),
                ('inapp_leave_status', models.BooleanField(default=True)),
                ('inapp_system_announcements', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False, help_text='Receive daily summary email')),
                ('weekly_digest', models.BooleanField(default=False, help_text='Receive weekly summary email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT_NEW', 'New Assignment'), ('ASSIGNMENT_REMINDER', 'Assignment Reminder'), ('ASSIGNMENT_EXPIRED', 'Assignment Expired'), ('ASSIGNMENT_CANCELLED', 'Assignment Cancelled'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('TIMETABLE_UPDATED', 'Timetable Updated'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to related object', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete after this date', null=True)),
                ('related_assignment_id', models.IntegerField(blank=True, null=True)),
                ('related_leave_id', models.IntegerField(blank=True, null=True)),
                ('related_exam_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
